---
abstract: 'Diff two arrays'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Array-Diff
no_index:
  directory:
    - inc
    - t
recommends:
  Algorithm::Diff::XS: 0
requires:
  Algorithm::Diff: 0
  Class::Accessor::Fast: 0
version: 0.05
